[versions]
# Build Config
agp = "8.13.1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"

# Language & Runtime
kotlin = "2.2.21"
# kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"

# UI Framework & Compose
compose = "1.9.3"
compose-compiler = "2.2.21"
compose-hot-reload = "1.0.0-rc04"
androidx-activity = "1.12.0"
material3-adaptive = "1.2.0"

# AndroidX
androidx-lifecycle = "2.9.6"

# Dependency Injection
koin = "4.1.1"

# Image Loading
coil = "3.3.0"

# Navigation
navigation-compose = "2.9.1"

# Firebase
firebase-bom = "34.6.0"
google-services-plugin = "4.4.4"

# ===========================

[libraries]
# Language & Runtime
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
# kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# UI & Compose
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }

# Material 3 Adaptive
material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" }
material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "material3-adaptive" }

# AndroidX Lifecycle
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }

# Navigation Compose
jetbrains-compose-navigation = { module ="org.jetbrains.androidx.navigation:navigation-compose", version.ref ="navigation-compose" }

# Dependency Injection (Koin)
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }


# Image Loading (Coil)
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" } # Alias simplificado
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }

# ===========================

[plugins]
# Android
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

# Kotlin & Compose
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose-compiler" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }

# Serialization
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Firebase
google-services = { id = "com.google.gms.google-services", version.ref = "google-services-plugin" }

# iOS - Cocoapods
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }

[bundles]
# AndroidX Lifecycle
androidx-lifecycle = [
    "androidx-lifecycle-viewmodel",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-savedstate"
]

# Dependency Injection (Koin)
koin-common = [
    "koin-core",
    "koin-compose",
    "koin-compose-viewmodel"
]

koin-android = [
    "koin-android",
]
